# Generated by Django 3.0.5 on 2020-04-19 11:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='accounts.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='com_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
