# Generated by Django 3.0.5 on 2020-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_debate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
