# Generated by Django 3.0.5 on 2020-05-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200517_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='side',
            field=models.CharField(default='defence', max_length=50),
        ),
    ]
